export enum AIIntent {
  GENERAL_CONVERSATION = 'GENERAL_CONVERSATION',
  CUSTOMER_LOOKUP = 'CUSTOMER_LOOKUP',
  SERVICE_INFORMATION = 'SERVICE_INFORMATION',
  STAFF_INFORMATION = 'STAFF_INFORMATION',
  APPOINTMENT_AVAILABILITY = 'APPOINTMENT_AVAILABILITY',
  BOOK_APPOINTMENT = 'BOOK_APPOINTMENT',
  VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS',
  CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
  RESCHEDULE_APPOINTMENT = 'RESCHEDULE_APPOINTMENT',
  BUSINESS_INFORMATION = 'BUSINESS_INFORMATION',
  UNKNOWN = 'UNKNOWN',
}
